### ISSUE TITLE
Issue in mobile view.

### ISSUE THREAD

**Issue by vaishalparikh** [vaishalparikh/Personal_Portfolio#2]
on mobile view after clicking on the toggle button, there is no cross button for closing the toggle

![WhatsApp Image 2022-07-26 at 10 18 19 PM](https://user-images.githubusercontent.com/86185385/181064956-eac1c19e-ef60-45b9-8e9b-9a769a777f00.jpeg)
.

**Comment by hardikgandhi03** [comment]
I want to contribute and solve this issue!

**Comment by vaishalparikh** [comment]
@hardikgandhi03 go for it.
